config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :offers do
    collection do
      post 'search', to: 'offers#search' 
      get 'search', to: 'offers#search' 
      get 'list_offers', to: 'offers#list_offers'
    end
    get :autocomplete_city_name, :on => :collection
  end
  resources :orders
  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country


	def auto_methode
		"#{self.name}, #{self.country.name}"
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
end

app/models/locomotive.rb
class Locomotive < ActiveRecord::Base
	belongs_to :user
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	include Wisper::Publisher
	after_create do
    	broadcast(:after_create, self)
  	end
	belongs_to :user


	def self.search_by_departure_and_destination(depart, dest)
		depart_city = depart.split(',').first
		depart_country = depart.split(',').last.strip

		dest_city = dest.split(',').first
		dest_country = dest.split(',').last.strip
		where(departure: depart_city, destination: dest_city, departure_country: depart_country, destination_country: dest_country)
	end
end

app/models/offer_observer.rb
class OfferObserver

	def after_create(offer)
		puts 'qjshfsjfhsdjfhsdjfhjdhf'
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :packets
end

app/models/packet.rb
class Packet < ActiveRecord::Base
	belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :locomotives
	has_many :orders
	has_many :offers
	has_many :comments
end

app/models/user_tracker.rb
class UserTracker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	autocomplete :city, :name, :full => true, :extra_data => [:country_id], :display_value => :auto_methode

	def index
		@offers = Offer.all
	end

	def new 
		@offer = Offer.new
	end

	def create
		@offer = Offer.new(offer_params)
		@offer.save

		respond_to do |format|
			format.html{ redirect_to offers_path }
		end
	end


	def search
		depart = params[:offer][:departure]
		dest = params[:offer][:destination]
		@offers = Offer.search_by_departure_and_destination(depart, dest)

		respond_to do |format|
			format.js
		end
	end

	def list_offers
		@offers = Offer.all

		respond_to do |format|
			format.js
		end
	end

	private 

	def offer_params
		 params.require(:offer).permit(:departure, :destination, :min_weight_accepted, :max_weight_accepted, :price, :departure_country, :destination_country, :user_id)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/_footer.html.erb
<!-- Footer -->
<div id="footer-wrapper">
	<footer id="footer" class="container">
		<div class="row">
			<div class="3u">
			
				<!-- Links -->
					<section class="widget links">
						<h3>Random Stuff</h3>
						<ul class="style2">
							<li><a href="#">Etiam feugiat condimentum</a></li>
							<li><a href="#">Aliquam imperdiet suscipit odio</a></li>
							<li><a href="#">Sed porttitor cras in erat nec</a></li>
							<li><a href="#">Felis varius pellentesque potenti</a></li>
							<li><a href="#">Nullam scelerisque blandit leo</a></li>
						</ul>
					</section>
			
			</div>
			<div class="3u">
			
				<!-- Links -->
					<section class="widget links">
						<h3>Random Stuff</h3>
						<ul class="style2">
							<li><a href="#">Etiam feugiat condimentum</a></li>
							<li><a href="#">Aliquam imperdiet suscipit odio</a></li>
							<li><a href="#">Sed porttitor cras in erat nec</a></li>
							<li><a href="#">Felis varius pellentesque potenti</a></li>
							<li><a href="#">Nullam scelerisque blandit leo</a></li>
						</ul>
					</section>
			
			</div>
			<div class="3u">
			
				<!-- Links -->
					<section class="widget links">
						<h3>Random Stuff</h3>
						<ul class="style2">
							<li><a href="#">Etiam feugiat condimentum</a></li>
							<li><a href="#">Aliquam imperdiet suscipit odio</a></li>
							<li><a href="#">Sed porttitor cras in erat nec</a></li>
							<li><a href="#">Felis varius pellentesque potenti</a></li>
							<li><a href="#">Nullam scelerisque blandit leo</a></li>
						</ul>
					</section>
			
			</div>
			<div class="3u">
			
				<!-- Contact -->
					<section class="widget contact last">
						<h3>Contact Us</h3>
						<ul>
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-pinterest"><span class="label">Pinterest</span></a></li>
						</ul>
						<p>1234 Fictional Road<br />
						Nashville, TN 00000<br />
						(800) 555-0000</p>
					</section>
			
			</div>
		</div>
		<div class="row">
			<div class="12u">
				<div id="copyright">
					<ul class="menu">
						<li>&copy; BEP. All rights reserved</li> <li> <%=link_to 'Equipe BEP', '#'%></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</div>

app/views/home/index.html.erb
	<!-- Banner -->
	<div id="banner-wrapper">
		<div id="banner" class="box container">
			<div class="row">
				<div class="7u">
					<h2>Bagage Entre Particuliers</h2>
					<p>la solution écologique et pas cher des transport des bagages</p>
				</div>
				<div class="5u">
					<ul>
						<li><%=link_to 'Expediteurs', offers_path, class: 'button big icon fa-cubes'%></li>
						<li><%=link_to 'Transporteurs', orders_path, class: 'button alt big icon fa-cab'%></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class='clear'></div>
	<div>
		<table class='default' >
			<thead>
				<tr>
					<th>depart</th>
					<th>destination</th>
				</tr>
			</thead>
			<tbody>
				<% Offer.all.each do |offer|%>
					<tr>
						<td><%= offer.departure %></td>
						<td><%= offer.destination %></td>
					</tr>		
				<% end %>
			</tbody>
		</table>
		
	</div>



	<%=render 'footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BEP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='homepage'>
	<div id='header-wrapper'>
		<%= yield %>
	</div>
</body>
</html>

app/views/offers/_list.html.erb
<div class='list'>
	<table class='default'>
		<thead>
			<th>user</th>
			<th>depart</th>
			<th>destination</th>
			<th>poids min</th>
			<th>poids max</th>
			<th>prix</th>
			<th>note</th>
		</thead>
		<tbody>
		<% offers.each do |offer| %>
			<tr>
				<td><%= offer.user.email%></td>
				<td><%= offer.departure %></td>
				<td><%= offer.destination %></td>
				<td><%= offer.min_weight_accepted %></td>
				<td><%= offer.max_weight_accepted %></td>
				<td><%= offer.price %></td>
				<td><%= offer.user.marx %></td>
			</tr>
		<%end%>	
		</tbody>
	</table>
</div>

app/views/offers/create.js.erb
alert('hhhh')

app/views/offers/index.html.erb
<h1>offres</h1>
<%= form_for(:offer, url: {controller: 'offers', action: 'search'}, remote: true) do |f|%>
	<%= f.autocomplete_field :departure, autocomplete_city_name_offers_path %>
	<%= f.autocomplete_field :destination, autocomplete_city_name_offers_path %>
	<%= f.submit 'search ' %>
<% end %>


<div id="search_result">
</div>

app/views/offers/list_offers.js.erb
alert('hhhh')

app/views/offers/new.html.erb
<%= form_for @offer do |f|%>
	<%=f.text_field :departure%>
	<%=f.text_field :destination%>
	<%#=f.text_field :min_weight_accepted%>
	<%#=f.text_field :max_weight_accepted%>
	<%=f.submit%>
<%end%>

app/views/offers/search.js.erb
<% unless @offers.blank? %>
	$('#search_result').html("<%=j render 'list', offers: @offers %>")
<% else %>
	$('#search_result').empty();
	$('#search_result').html('<p>No result</p>')
<% end %>

app/views/orders/index.html.erb
<h1>commande</h1>